services:
  db:
    image: postgres:16
    container_name: bhcaptureco_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bhcaptureco
    ports:
      - "5432:5432"
    volumes:
      - bhcaptureco_pgdata:/var/lib/postgresql/data

volumes:
  bhcaptureco_pgdata: